SERVICE_NAME=CotizadorPocketBase
DISPLAY_NAME=Cotizador PocketBase
BIND_ADDR=127.0.0.1:8090
BACKEND_URL=http://127.0.0.1:8090
PUBLIC_DIR=frontend\pb_public
HTTPS_ENABLED=0
HTTPS_HOST=
HTTPS_PORT=9443
HTTPS_CERT_THUMBPRINT=
HTTPS_CERT_FILE=
